### ISSUE TITLE
revise: update the permissible values for file type

### ISSUE THREAD

**Issue by claymcleod** [CBIIT/ccdi-federation-api#127]
Since the release of the file type CDE (`11416926`), the following values have been added. The API needs to be updated to reflect this.

- `CNS`
- `DICT`
- `DOC`
- `HTSeq Count`
- `PED`
- `RTF`
- `SEG`
- `TBI`
- `cdf`
- `gVCF`
- `idpDB`
- `rds`

**Comment by GeoffLyle** [comment]
After a first pass of these new PVs, I don't see any glaring issues in including them in the API implementation of the CDE (a minor thing is why some extensions are capitalized and others are not, but that is not a major issue.  It would be preferable to have the data harmonization members from each group review and confirm these are okay to be implemented, either in this issue or in a group meeting.  How and when this update should occur is up to the API implementation leads, whether it be a small update or rolled into a larger update.  As this does not directly affect any members who would not use the new values (I don't believe Federation members would have to update their local implementation of the code), I favor a quicker, smaller update.
There are concerns that updates are made to CDEs that the CCDI Federation is not aware of.  @jknable Can you provide more information on when a new version of a CDE is released (ex. v2).  It is my impression that Permissible Values may be added to a CDE without the need to release a new version, but if Permissible values are removed or redefined, a new version of the CDE would need to be released.

**Comment by claymcleod** [comment]
Given the fast turnaround time needed, the low risk for this becoming an issue for federation members (they simply don't have to use the values if they don't want to), _AND_ Geoff's comment above, I've decided to go ahead and merge these changes in to make it into v1.1.0.
