### ISSUE TITLE
"sample" "anatomical_sites" search filter has a different name than the attribute under the search

### ISSUE THREAD

**Issue by asafieva** [CBIIT/ccdi-federation-api#128]
**Please describe the problem you're having**
"sample" "anatomical_sites" search filter has a different name than the attribute under the search. They are expected to be the same. 

**To Reproduce**
1. Go to 'https://cbiit.github.io/ccdi-federation-api/specification.html' and select UCSC server.
2. Click on 'sample'>>'GET'
3. Scroll down to 'anatomical_site' parameter and enter "chest".
4. See an error "Invalid parameter(s): anatomical_site."

**Expected behavior**
UCSC has data for "anatomical_sites" attribute. Here is a URL which return search results by a filter "**anatomical_sites**":
https://ccdi.treehouse.gi.ucsc.edu/api/v1/sample?anatomical_sites=chest&per_page=1

**Additional context**
Most attribute names are **singular** even for _array_ attributes, as an example "subject">>"race". But plural noun form was also used for some attributes' names as "depositions", with the same corresponding search filter name.
We'd better correct OpenAPI spec to use the same search filter names as corresponding attribute names. 
UCSC and KidsFirst use "anatomical_sites" (plural) for both sample's attribute name and the search filter name in their v1.1.0 implementations as of 12/16/2024.

**Comment by claymcleod** [comment]
Yeah, this is intended to be plural. I will update it. Thank you for the report!
