### ISSUE TITLE
Wiki page error on "Subject-Metadata-Fields" page in values for attribute "race"

### ISSUE THREAD

**Issue by asafieva** [CBIIT/ccdi-federation-api#129]
**Please describe the problem you're having**
"Subject-Metadata-Fields" attribute "race": "Asian" PV is listed twice, and PV "Black or African American" is missing.

**To Reproduce**
1. Go to [race](https://github.com/CBIIT/ccdi-federation-api/wiki/Subject-Metadata-Fields#race)
2. Scroll down to caDSR CDE [2192199](https://cadsr.cancer.gov/onedata/dmdirect/NIH/NCI/CO/CDEDD?filter=CDEDD.ITEM_ID=2192199%20and%20ver_nr=1)
4. See an error in PV list that one PV, Asian, is listed twice and one PV, "Black or African American", is missing.

**Expected behavior**
We shall see eight different PVs from caDSR CDE [2192199](https://cadsr.cancer.gov/onedata/dmdirect/NIH/NCI/CO/CDEDD?filter=CDEDD.ITEM_ID=2192199%20and%20ver_nr=1)

**Comment by claymcleod** [comment]
@grugna or @e-t-k, any takers?

**Comment by claymcleod** [comment]
It ended up being simple, so I just went ahead and corrected it.
